// Generated by CoffeeScript 1.7.1
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var HDimgs, image, img, _i, _len, _results;
    HDimgs = document.querySelectorAll('[srcset]');
    _results = [];
    for (_i = 0, _len = HDimgs.length; _i < _len; _i++) {
      img = HDimgs[_i];
      _results.push((image = new Image(), image.onload = function() {
        console.info('Image loaded');
        img.src = image.src;
        img.style.width = "" + (image.width / 2) + "px";
        return img.removeAttribute('srcset');
      }, image.onerror = function() {
        return console.error('Could not load image');
      }, image.src = img.srcset.split(' ')[0]));
    }
    return _results;
  });

}).call(this);
